### ISSUE TITLE
pymux BetterScreen / BetterStream

### ISSUE THREAD

**Issue by crdoconnor** [selectel/pyte#60]
Hi,

I was wondering what you thought of pymux's BetterStream and BetterScreen?

https://github.com/jonathanslenders/pymux/blob/master/pymux/screen.py

Changes compared to the original `Screen` class:
    - We store the layout in a prompt_toolkit.layout.screen.Screen instance.
      This allows fast rendering in a prompt_toolkit user control.
    - 256 colour and true color support.
    - CPR support and device attributes.

https://github.com/jonathanslenders/pymux/blob/master/pymux/stream.py

    Extension to the Pyte `Stream` class that also handles "Esc]<num>...BEL"
    sequences. This is used by xterm to set the terminal title.

Are any of these fixes already in pyte? Would it be your intention to merge them back in? Can you see any potential issues with them?

**Comment by superbobry** [comment]
Hi, thanks for asking.

@jonathanslenders did great work on performance in `pymux` and there is work ongoing on backporting the improvements into `pyte`. Here's what's already in `master`:

* all of `BetterStream` in terms of functionality,
* 256/16bit colour support,
* CPR support

The remaining issue is replacing a `[[]]` with a `defaultdict` for `Screen.buffer`. It is somewhat complicated due to a complete lack of tests on the `pymux` side. Anyway, I'd be happy to merge a PR doing this.

**Comment by superbobry** [comment]
@istarion is currently evaluating the `defaultdict` migration. If the benchmarks are be positive, this would be merged into `master` soon.
